generator:
  class: sfPropelGenerator
  param:
    model_class:           MbMailto
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              MbMailto
    plural:                MbMailtos
    route_prefix:          mb_mailto
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: "Recipients list"
        display: [id, mail_id, mailto, state, error, sent_at]
        actions:
          new: ~
          export:
            label: "Download as xls"
          back:
            label: "Back to Today\'s mails"
      filter:
        display: [mail_id, mailto, state, sent_at]
      form:    ~
      edit:    ~
      new:     ~
