<?php



/**
 * This class defines the structure of the 'log_mailto' table.
 *
 *
 * This class was autogenerated by Propel 1.5.3-dev on:
 *
 * Wed Aug  4 22:47:56 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class LogMailtoTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.LogMailtoTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('log_mailto');
		$this->setPhpName('LogMailto');
		$this->setClassname('LogMailto');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('MAIL_ID', 'MailId', 'INTEGER', 'log_mail', 'ID', false, null, null);
		$this->addColumn('MAILTO', 'Mailto', 'VARCHAR', false, 255, null);
		$this->addColumn('STATE', 'State', 'VARCHAR', false, 50, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('SENT_AT', 'SentAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('TRIES', 'Tries', 'TINYINT', false, null, null);
		$this->addColumn('ERROR', 'Error', 'LONGVARCHAR', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('LogMail', 'LogMail', RelationMap::MANY_TO_ONE, array('mail_id' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // LogMailtoTableMap
