<?php



/**
 * This class defines the structure of the 'mb_mail' table.
 *
 *
 * This class was autogenerated by Propel 1.5.3-dev on:
 *
 * Wed Aug  4 22:47:56 2010
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class MbMailTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.MbMailTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('mb_mail');
		$this->setPhpName('MbMail');
		$this->setClassname('MbMail');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('USERNAME', 'Username', 'VARCHAR', false, 255, null);
		$this->addColumn('BODY_HTML', 'BodyHtml', 'LONGVARCHAR', false, null, null);
		$this->addColumn('BODY_TEXT', 'BodyText', 'LONGVARCHAR', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('SUBJECT', 'Subject', 'VARCHAR', false, 255, null);
		$this->addColumn('STRFROM', 'Strfrom', 'VARCHAR', false, 255, null);
		$this->addColumn('REPLY_TO', 'ReplyTo', 'VARCHAR', false, 255, null);
		$this->addColumn('NOTIFY_TO', 'NotifyTo', 'VARCHAR', false, 255, null);
		$this->addColumn('PLATFORM', 'Platform', 'VARCHAR', false, 50, null);
		$this->addColumn('PUBLIC_PATH', 'PublicPath', 'VARCHAR', false, 255, null);
		$this->addColumn('BATCH_SIZE', 'BatchSize', 'TINYINT', false, null, 10);
		$this->addColumn('STATE', 'State', 'VARCHAR', false, 50, null);
		$this->addColumn('ERROR', 'Error', 'VARCHAR', false, 255, null);
		$this->addColumn('TOKEN', 'Token', 'VARCHAR', false, 255, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('MbMailto', 'MbMailto', RelationMap::ONE_TO_MANY, array('id' => 'mail_id', ), 'CASCADE', null);
    $this->addRelation('MbMailAttachment', 'MbMailAttachment', RelationMap::ONE_TO_MANY, array('id' => 'mail_id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // MbMailTableMap
