<?php


/**
 * Base class that represents a query for the 'mb_mail_attachment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3-dev on:
 *
 * Wed Aug  4 22:47:56 2010
 *
 * @method     MbMailAttachmentQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     MbMailAttachmentQuery orderByMailId($order = Criteria::ASC) Order by the mail_id column
 * @method     MbMailAttachmentQuery orderByUrl($order = Criteria::ASC) Order by the url column
 * @method     MbMailAttachmentQuery orderByType($order = Criteria::ASC) Order by the type column
 *
 * @method     MbMailAttachmentQuery groupById() Group by the id column
 * @method     MbMailAttachmentQuery groupByMailId() Group by the mail_id column
 * @method     MbMailAttachmentQuery groupByUrl() Group by the url column
 * @method     MbMailAttachmentQuery groupByType() Group by the type column
 *
 * @method     MbMailAttachmentQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     MbMailAttachmentQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     MbMailAttachmentQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     MbMailAttachmentQuery leftJoinMbMail($relationAlias = '') Adds a LEFT JOIN clause to the query using the MbMail relation
 * @method     MbMailAttachmentQuery rightJoinMbMail($relationAlias = '') Adds a RIGHT JOIN clause to the query using the MbMail relation
 * @method     MbMailAttachmentQuery innerJoinMbMail($relationAlias = '') Adds a INNER JOIN clause to the query using the MbMail relation
 *
 * @method     MbMailAttachment findOne(PropelPDO $con = null) Return the first MbMailAttachment matching the query
 * @method     MbMailAttachment findOneOrCreate(PropelPDO $con = null) Return the first MbMailAttachment matching the query, or a new MbMailAttachment object populated from the query conditions when no match is found
 *
 * @method     MbMailAttachment findOneById(int $id) Return the first MbMailAttachment filtered by the id column
 * @method     MbMailAttachment findOneByMailId(int $mail_id) Return the first MbMailAttachment filtered by the mail_id column
 * @method     MbMailAttachment findOneByUrl(string $url) Return the first MbMailAttachment filtered by the url column
 * @method     MbMailAttachment findOneByType(string $type) Return the first MbMailAttachment filtered by the type column
 *
 * @method     array findById(int $id) Return MbMailAttachment objects filtered by the id column
 * @method     array findByMailId(int $mail_id) Return MbMailAttachment objects filtered by the mail_id column
 * @method     array findByUrl(string $url) Return MbMailAttachment objects filtered by the url column
 * @method     array findByType(string $type) Return MbMailAttachment objects filtered by the type column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseMbMailAttachmentQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseMbMailAttachmentQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'MbMailAttachment', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new MbMailAttachmentQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    MbMailAttachmentQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof MbMailAttachmentQuery) {
			return $criteria;
		}
		$query = new MbMailAttachmentQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    MbMailAttachment|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = MbMailAttachmentPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    MbMailAttachmentQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(MbMailAttachmentPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    MbMailAttachmentQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(MbMailAttachmentPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     int|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailAttachmentQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(MbMailAttachmentPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the mail_id column
	 * 
	 * @param     int|array $mailId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailAttachmentQuery The current query, for fluid interface
	 */
	public function filterByMailId($mailId = null, $comparison = null)
	{
		if (is_array($mailId)) {
			$useMinMax = false;
			if (isset($mailId['min'])) {
				$this->addUsingAlias(MbMailAttachmentPeer::MAIL_ID, $mailId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($mailId['max'])) {
				$this->addUsingAlias(MbMailAttachmentPeer::MAIL_ID, $mailId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(MbMailAttachmentPeer::MAIL_ID, $mailId, $comparison);
	}

	/**
	 * Filter the query on the url column
	 * 
	 * @param     string $url The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailAttachmentQuery The current query, for fluid interface
	 */
	public function filterByUrl($url = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($url)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $url)) {
				$url = str_replace('*', '%', $url);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailAttachmentPeer::URL, $url, $comparison);
	}

	/**
	 * Filter the query on the type column
	 * 
	 * @param     string $type The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailAttachmentQuery The current query, for fluid interface
	 */
	public function filterByType($type = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($type)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $type)) {
				$type = str_replace('*', '%', $type);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailAttachmentPeer::TYPE, $type, $comparison);
	}

	/**
	 * Filter the query by a related MbMail object
	 *
	 * @param     MbMail $mbMail  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailAttachmentQuery The current query, for fluid interface
	 */
	public function filterByMbMail($mbMail, $comparison = null)
	{
		return $this
			->addUsingAlias(MbMailAttachmentPeer::MAIL_ID, $mbMail->getId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the MbMail relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MbMailAttachmentQuery The current query, for fluid interface
	 */
	public function joinMbMail($relationAlias = '', $joinType = Criteria::LEFT_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('MbMail');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'MbMail');
		}
		
		return $this;
	}

	/**
	 * Use the MbMail relation MbMail object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MbMailQuery A secondary query class using the current class as primary query
	 */
	public function useMbMailQuery($relationAlias = '', $joinType = Criteria::LEFT_JOIN)
	{
		return $this
			->joinMbMail($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'MbMail', 'MbMailQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     MbMailAttachment $mbMailAttachment Object to remove from the list of results
	 *
	 * @return    MbMailAttachmentQuery The current query, for fluid interface
	 */
	public function prune($mbMailAttachment = null)
	{
		if ($mbMailAttachment) {
			$this->addUsingAlias(MbMailAttachmentPeer::ID, $mbMailAttachment->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseMbMailAttachmentQuery
