<?php


/**
 * Base class that represents a query for the 'mb_mailto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3-dev on:
 *
 * Wed Aug  4 22:47:56 2010
 *
 * @method     MbMailtoQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     MbMailtoQuery orderByMailId($order = Criteria::ASC) Order by the mail_id column
 * @method     MbMailtoQuery orderByMailto($order = Criteria::ASC) Order by the mailto column
 * @method     MbMailtoQuery orderByState($order = Criteria::ASC) Order by the state column
 * @method     MbMailtoQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method     MbMailtoQuery orderBySentAt($order = Criteria::ASC) Order by the sent_at column
 * @method     MbMailtoQuery orderByTries($order = Criteria::ASC) Order by the tries column
 * @method     MbMailtoQuery orderByError($order = Criteria::ASC) Order by the error column
 *
 * @method     MbMailtoQuery groupById() Group by the id column
 * @method     MbMailtoQuery groupByMailId() Group by the mail_id column
 * @method     MbMailtoQuery groupByMailto() Group by the mailto column
 * @method     MbMailtoQuery groupByState() Group by the state column
 * @method     MbMailtoQuery groupByCreatedAt() Group by the created_at column
 * @method     MbMailtoQuery groupBySentAt() Group by the sent_at column
 * @method     MbMailtoQuery groupByTries() Group by the tries column
 * @method     MbMailtoQuery groupByError() Group by the error column
 *
 * @method     MbMailtoQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     MbMailtoQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     MbMailtoQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     MbMailtoQuery leftJoinMbMail($relationAlias = '') Adds a LEFT JOIN clause to the query using the MbMail relation
 * @method     MbMailtoQuery rightJoinMbMail($relationAlias = '') Adds a RIGHT JOIN clause to the query using the MbMail relation
 * @method     MbMailtoQuery innerJoinMbMail($relationAlias = '') Adds a INNER JOIN clause to the query using the MbMail relation
 *
 * @method     MbMailto findOne(PropelPDO $con = null) Return the first MbMailto matching the query
 * @method     MbMailto findOneOrCreate(PropelPDO $con = null) Return the first MbMailto matching the query, or a new MbMailto object populated from the query conditions when no match is found
 *
 * @method     MbMailto findOneById(int $id) Return the first MbMailto filtered by the id column
 * @method     MbMailto findOneByMailId(int $mail_id) Return the first MbMailto filtered by the mail_id column
 * @method     MbMailto findOneByMailto(string $mailto) Return the first MbMailto filtered by the mailto column
 * @method     MbMailto findOneByState(string $state) Return the first MbMailto filtered by the state column
 * @method     MbMailto findOneByCreatedAt(string $created_at) Return the first MbMailto filtered by the created_at column
 * @method     MbMailto findOneBySentAt(string $sent_at) Return the first MbMailto filtered by the sent_at column
 * @method     MbMailto findOneByTries(int $tries) Return the first MbMailto filtered by the tries column
 * @method     MbMailto findOneByError(string $error) Return the first MbMailto filtered by the error column
 *
 * @method     array findById(int $id) Return MbMailto objects filtered by the id column
 * @method     array findByMailId(int $mail_id) Return MbMailto objects filtered by the mail_id column
 * @method     array findByMailto(string $mailto) Return MbMailto objects filtered by the mailto column
 * @method     array findByState(string $state) Return MbMailto objects filtered by the state column
 * @method     array findByCreatedAt(string $created_at) Return MbMailto objects filtered by the created_at column
 * @method     array findBySentAt(string $sent_at) Return MbMailto objects filtered by the sent_at column
 * @method     array findByTries(int $tries) Return MbMailto objects filtered by the tries column
 * @method     array findByError(string $error) Return MbMailto objects filtered by the error column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseMbMailtoQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseMbMailtoQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'MbMailto', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new MbMailtoQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    MbMailtoQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof MbMailtoQuery) {
			return $criteria;
		}
		$query = new MbMailtoQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    MbMailto|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = MbMailtoPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    MbMailtoQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(MbMailtoPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    MbMailtoQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(MbMailtoPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     int|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailtoQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(MbMailtoPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the mail_id column
	 * 
	 * @param     int|array $mailId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailtoQuery The current query, for fluid interface
	 */
	public function filterByMailId($mailId = null, $comparison = null)
	{
		if (is_array($mailId)) {
			$useMinMax = false;
			if (isset($mailId['min'])) {
				$this->addUsingAlias(MbMailtoPeer::MAIL_ID, $mailId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($mailId['max'])) {
				$this->addUsingAlias(MbMailtoPeer::MAIL_ID, $mailId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(MbMailtoPeer::MAIL_ID, $mailId, $comparison);
	}

	/**
	 * Filter the query on the mailto column
	 * 
	 * @param     string $mailto The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailtoQuery The current query, for fluid interface
	 */
	public function filterByMailto($mailto = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($mailto)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $mailto)) {
				$mailto = str_replace('*', '%', $mailto);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailtoPeer::MAILTO, $mailto, $comparison);
	}

	/**
	 * Filter the query on the state column
	 * 
	 * @param     string $state The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailtoQuery The current query, for fluid interface
	 */
	public function filterByState($state = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($state)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $state)) {
				$state = str_replace('*', '%', $state);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailtoPeer::STATE, $state, $comparison);
	}

	/**
	 * Filter the query on the created_at column
	 * 
	 * @param     string|array $createdAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailtoQuery The current query, for fluid interface
	 */
	public function filterByCreatedAt($createdAt = null, $comparison = null)
	{
		if (is_array($createdAt)) {
			$useMinMax = false;
			if (isset($createdAt['min'])) {
				$this->addUsingAlias(MbMailtoPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($createdAt['max'])) {
				$this->addUsingAlias(MbMailtoPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(MbMailtoPeer::CREATED_AT, $createdAt, $comparison);
	}

	/**
	 * Filter the query on the sent_at column
	 * 
	 * @param     string|array $sentAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailtoQuery The current query, for fluid interface
	 */
	public function filterBySentAt($sentAt = null, $comparison = null)
	{
		if (is_array($sentAt)) {
			$useMinMax = false;
			if (isset($sentAt['min'])) {
				$this->addUsingAlias(MbMailtoPeer::SENT_AT, $sentAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($sentAt['max'])) {
				$this->addUsingAlias(MbMailtoPeer::SENT_AT, $sentAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(MbMailtoPeer::SENT_AT, $sentAt, $comparison);
	}

	/**
	 * Filter the query on the tries column
	 * 
	 * @param     int|array $tries The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailtoQuery The current query, for fluid interface
	 */
	public function filterByTries($tries = null, $comparison = null)
	{
		if (is_array($tries)) {
			$useMinMax = false;
			if (isset($tries['min'])) {
				$this->addUsingAlias(MbMailtoPeer::TRIES, $tries['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($tries['max'])) {
				$this->addUsingAlias(MbMailtoPeer::TRIES, $tries['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(MbMailtoPeer::TRIES, $tries, $comparison);
	}

	/**
	 * Filter the query on the error column
	 * 
	 * @param     string $error The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailtoQuery The current query, for fluid interface
	 */
	public function filterByError($error = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($error)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $error)) {
				$error = str_replace('*', '%', $error);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailtoPeer::ERROR, $error, $comparison);
	}

	/**
	 * Filter the query by a related MbMail object
	 *
	 * @param     MbMail $mbMail  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailtoQuery The current query, for fluid interface
	 */
	public function filterByMbMail($mbMail, $comparison = null)
	{
		return $this
			->addUsingAlias(MbMailtoPeer::MAIL_ID, $mbMail->getId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the MbMail relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MbMailtoQuery The current query, for fluid interface
	 */
	public function joinMbMail($relationAlias = '', $joinType = Criteria::LEFT_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('MbMail');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'MbMail');
		}
		
		return $this;
	}

	/**
	 * Use the MbMail relation MbMail object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MbMailQuery A secondary query class using the current class as primary query
	 */
	public function useMbMailQuery($relationAlias = '', $joinType = Criteria::LEFT_JOIN)
	{
		return $this
			->joinMbMail($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'MbMail', 'MbMailQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     MbMailto $mbMailto Object to remove from the list of results
	 *
	 * @return    MbMailtoQuery The current query, for fluid interface
	 */
	public function prune($mbMailto = null)
	{
		if ($mbMailto) {
			$this->addUsingAlias(MbMailtoPeer::ID, $mbMailto->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseMbMailtoQuery
