<?php


/**
 * Base class that represents a query for the 'mb_mail' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3-dev on:
 *
 * Wed Aug  4 22:47:56 2010
 *
 * @method     MbMailQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     MbMailQuery orderByUsername($order = Criteria::ASC) Order by the username column
 * @method     MbMailQuery orderByBodyHtml($order = Criteria::ASC) Order by the body_html column
 * @method     MbMailQuery orderByBodyText($order = Criteria::ASC) Order by the body_text column
 * @method     MbMailQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method     MbMailQuery orderBySubject($order = Criteria::ASC) Order by the subject column
 * @method     MbMailQuery orderByStrfrom($order = Criteria::ASC) Order by the strfrom column
 * @method     MbMailQuery orderByReplyTo($order = Criteria::ASC) Order by the reply_to column
 * @method     MbMailQuery orderByNotifyTo($order = Criteria::ASC) Order by the notify_to column
 * @method     MbMailQuery orderByPlatform($order = Criteria::ASC) Order by the platform column
 * @method     MbMailQuery orderByPublicPath($order = Criteria::ASC) Order by the public_path column
 * @method     MbMailQuery orderByBatchSize($order = Criteria::ASC) Order by the batch_size column
 * @method     MbMailQuery orderByState($order = Criteria::ASC) Order by the state column
 * @method     MbMailQuery orderByError($order = Criteria::ASC) Order by the error column
 * @method     MbMailQuery orderByToken($order = Criteria::ASC) Order by the token column
 *
 * @method     MbMailQuery groupById() Group by the id column
 * @method     MbMailQuery groupByUsername() Group by the username column
 * @method     MbMailQuery groupByBodyHtml() Group by the body_html column
 * @method     MbMailQuery groupByBodyText() Group by the body_text column
 * @method     MbMailQuery groupByCreatedAt() Group by the created_at column
 * @method     MbMailQuery groupBySubject() Group by the subject column
 * @method     MbMailQuery groupByStrfrom() Group by the strfrom column
 * @method     MbMailQuery groupByReplyTo() Group by the reply_to column
 * @method     MbMailQuery groupByNotifyTo() Group by the notify_to column
 * @method     MbMailQuery groupByPlatform() Group by the platform column
 * @method     MbMailQuery groupByPublicPath() Group by the public_path column
 * @method     MbMailQuery groupByBatchSize() Group by the batch_size column
 * @method     MbMailQuery groupByState() Group by the state column
 * @method     MbMailQuery groupByError() Group by the error column
 * @method     MbMailQuery groupByToken() Group by the token column
 *
 * @method     MbMailQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     MbMailQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     MbMailQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     MbMailQuery leftJoinMbMailto($relationAlias = '') Adds a LEFT JOIN clause to the query using the MbMailto relation
 * @method     MbMailQuery rightJoinMbMailto($relationAlias = '') Adds a RIGHT JOIN clause to the query using the MbMailto relation
 * @method     MbMailQuery innerJoinMbMailto($relationAlias = '') Adds a INNER JOIN clause to the query using the MbMailto relation
 *
 * @method     MbMailQuery leftJoinMbMailAttachment($relationAlias = '') Adds a LEFT JOIN clause to the query using the MbMailAttachment relation
 * @method     MbMailQuery rightJoinMbMailAttachment($relationAlias = '') Adds a RIGHT JOIN clause to the query using the MbMailAttachment relation
 * @method     MbMailQuery innerJoinMbMailAttachment($relationAlias = '') Adds a INNER JOIN clause to the query using the MbMailAttachment relation
 *
 * @method     MbMail findOne(PropelPDO $con = null) Return the first MbMail matching the query
 * @method     MbMail findOneOrCreate(PropelPDO $con = null) Return the first MbMail matching the query, or a new MbMail object populated from the query conditions when no match is found
 *
 * @method     MbMail findOneById(int $id) Return the first MbMail filtered by the id column
 * @method     MbMail findOneByUsername(string $username) Return the first MbMail filtered by the username column
 * @method     MbMail findOneByBodyHtml(string $body_html) Return the first MbMail filtered by the body_html column
 * @method     MbMail findOneByBodyText(string $body_text) Return the first MbMail filtered by the body_text column
 * @method     MbMail findOneByCreatedAt(string $created_at) Return the first MbMail filtered by the created_at column
 * @method     MbMail findOneBySubject(string $subject) Return the first MbMail filtered by the subject column
 * @method     MbMail findOneByStrfrom(string $strfrom) Return the first MbMail filtered by the strfrom column
 * @method     MbMail findOneByReplyTo(string $reply_to) Return the first MbMail filtered by the reply_to column
 * @method     MbMail findOneByNotifyTo(string $notify_to) Return the first MbMail filtered by the notify_to column
 * @method     MbMail findOneByPlatform(string $platform) Return the first MbMail filtered by the platform column
 * @method     MbMail findOneByPublicPath(string $public_path) Return the first MbMail filtered by the public_path column
 * @method     MbMail findOneByBatchSize(int $batch_size) Return the first MbMail filtered by the batch_size column
 * @method     MbMail findOneByState(string $state) Return the first MbMail filtered by the state column
 * @method     MbMail findOneByError(string $error) Return the first MbMail filtered by the error column
 * @method     MbMail findOneByToken(string $token) Return the first MbMail filtered by the token column
 *
 * @method     array findById(int $id) Return MbMail objects filtered by the id column
 * @method     array findByUsername(string $username) Return MbMail objects filtered by the username column
 * @method     array findByBodyHtml(string $body_html) Return MbMail objects filtered by the body_html column
 * @method     array findByBodyText(string $body_text) Return MbMail objects filtered by the body_text column
 * @method     array findByCreatedAt(string $created_at) Return MbMail objects filtered by the created_at column
 * @method     array findBySubject(string $subject) Return MbMail objects filtered by the subject column
 * @method     array findByStrfrom(string $strfrom) Return MbMail objects filtered by the strfrom column
 * @method     array findByReplyTo(string $reply_to) Return MbMail objects filtered by the reply_to column
 * @method     array findByNotifyTo(string $notify_to) Return MbMail objects filtered by the notify_to column
 * @method     array findByPlatform(string $platform) Return MbMail objects filtered by the platform column
 * @method     array findByPublicPath(string $public_path) Return MbMail objects filtered by the public_path column
 * @method     array findByBatchSize(int $batch_size) Return MbMail objects filtered by the batch_size column
 * @method     array findByState(string $state) Return MbMail objects filtered by the state column
 * @method     array findByError(string $error) Return MbMail objects filtered by the error column
 * @method     array findByToken(string $token) Return MbMail objects filtered by the token column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseMbMailQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseMbMailQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'MbMail', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new MbMailQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    MbMailQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof MbMailQuery) {
			return $criteria;
		}
		$query = new MbMailQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    MbMail|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = MbMailPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(MbMailPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(MbMailPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     int|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(MbMailPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the username column
	 * 
	 * @param     string $username The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByUsername($username = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($username)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $username)) {
				$username = str_replace('*', '%', $username);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailPeer::USERNAME, $username, $comparison);
	}

	/**
	 * Filter the query on the body_html column
	 * 
	 * @param     string $bodyHtml The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByBodyHtml($bodyHtml = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($bodyHtml)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $bodyHtml)) {
				$bodyHtml = str_replace('*', '%', $bodyHtml);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailPeer::BODY_HTML, $bodyHtml, $comparison);
	}

	/**
	 * Filter the query on the body_text column
	 * 
	 * @param     string $bodyText The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByBodyText($bodyText = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($bodyText)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $bodyText)) {
				$bodyText = str_replace('*', '%', $bodyText);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailPeer::BODY_TEXT, $bodyText, $comparison);
	}

	/**
	 * Filter the query on the created_at column
	 * 
	 * @param     string|array $createdAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByCreatedAt($createdAt = null, $comparison = null)
	{
		if (is_array($createdAt)) {
			$useMinMax = false;
			if (isset($createdAt['min'])) {
				$this->addUsingAlias(MbMailPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($createdAt['max'])) {
				$this->addUsingAlias(MbMailPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(MbMailPeer::CREATED_AT, $createdAt, $comparison);
	}

	/**
	 * Filter the query on the subject column
	 * 
	 * @param     string $subject The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterBySubject($subject = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($subject)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $subject)) {
				$subject = str_replace('*', '%', $subject);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailPeer::SUBJECT, $subject, $comparison);
	}

	/**
	 * Filter the query on the strfrom column
	 * 
	 * @param     string $strfrom The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByStrfrom($strfrom = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($strfrom)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $strfrom)) {
				$strfrom = str_replace('*', '%', $strfrom);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailPeer::STRFROM, $strfrom, $comparison);
	}

	/**
	 * Filter the query on the reply_to column
	 * 
	 * @param     string $replyTo The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByReplyTo($replyTo = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($replyTo)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $replyTo)) {
				$replyTo = str_replace('*', '%', $replyTo);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailPeer::REPLY_TO, $replyTo, $comparison);
	}

	/**
	 * Filter the query on the notify_to column
	 * 
	 * @param     string $notifyTo The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByNotifyTo($notifyTo = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($notifyTo)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $notifyTo)) {
				$notifyTo = str_replace('*', '%', $notifyTo);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailPeer::NOTIFY_TO, $notifyTo, $comparison);
	}

	/**
	 * Filter the query on the platform column
	 * 
	 * @param     string $platform The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByPlatform($platform = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($platform)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $platform)) {
				$platform = str_replace('*', '%', $platform);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailPeer::PLATFORM, $platform, $comparison);
	}

	/**
	 * Filter the query on the public_path column
	 * 
	 * @param     string $publicPath The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByPublicPath($publicPath = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($publicPath)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $publicPath)) {
				$publicPath = str_replace('*', '%', $publicPath);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailPeer::PUBLIC_PATH, $publicPath, $comparison);
	}

	/**
	 * Filter the query on the batch_size column
	 * 
	 * @param     int|array $batchSize The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByBatchSize($batchSize = null, $comparison = null)
	{
		if (is_array($batchSize)) {
			$useMinMax = false;
			if (isset($batchSize['min'])) {
				$this->addUsingAlias(MbMailPeer::BATCH_SIZE, $batchSize['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($batchSize['max'])) {
				$this->addUsingAlias(MbMailPeer::BATCH_SIZE, $batchSize['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(MbMailPeer::BATCH_SIZE, $batchSize, $comparison);
	}

	/**
	 * Filter the query on the state column
	 * 
	 * @param     string $state The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByState($state = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($state)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $state)) {
				$state = str_replace('*', '%', $state);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailPeer::STATE, $state, $comparison);
	}

	/**
	 * Filter the query on the error column
	 * 
	 * @param     string $error The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByError($error = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($error)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $error)) {
				$error = str_replace('*', '%', $error);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailPeer::ERROR, $error, $comparison);
	}

	/**
	 * Filter the query on the token column
	 * 
	 * @param     string $token The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByToken($token = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($token)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $token)) {
				$token = str_replace('*', '%', $token);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MbMailPeer::TOKEN, $token, $comparison);
	}

	/**
	 * Filter the query by a related MbMailto object
	 *
	 * @param     MbMailto $mbMailto  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByMbMailto($mbMailto, $comparison = null)
	{
		return $this
			->addUsingAlias(MbMailPeer::ID, $mbMailto->getMailId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the MbMailto relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function joinMbMailto($relationAlias = '', $joinType = Criteria::LEFT_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('MbMailto');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'MbMailto');
		}
		
		return $this;
	}

	/**
	 * Use the MbMailto relation MbMailto object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MbMailtoQuery A secondary query class using the current class as primary query
	 */
	public function useMbMailtoQuery($relationAlias = '', $joinType = Criteria::LEFT_JOIN)
	{
		return $this
			->joinMbMailto($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'MbMailto', 'MbMailtoQuery');
	}

	/**
	 * Filter the query by a related MbMailAttachment object
	 *
	 * @param     MbMailAttachment $mbMailAttachment  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function filterByMbMailAttachment($mbMailAttachment, $comparison = null)
	{
		return $this
			->addUsingAlias(MbMailPeer::ID, $mbMailAttachment->getMailId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the MbMailAttachment relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function joinMbMailAttachment($relationAlias = '', $joinType = Criteria::LEFT_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('MbMailAttachment');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'MbMailAttachment');
		}
		
		return $this;
	}

	/**
	 * Use the MbMailAttachment relation MbMailAttachment object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MbMailAttachmentQuery A secondary query class using the current class as primary query
	 */
	public function useMbMailAttachmentQuery($relationAlias = '', $joinType = Criteria::LEFT_JOIN)
	{
		return $this
			->joinMbMailAttachment($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'MbMailAttachment', 'MbMailAttachmentQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     MbMail $mbMail Object to remove from the list of results
	 *
	 * @return    MbMailQuery The current query, for fluid interface
	 */
	public function prune($mbMail = null)
	{
		if ($mbMail) {
			$this->addUsingAlias(MbMailPeer::ID, $mbMail->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseMbMailQuery
