<?php


/**
 * Base class that represents a query for the 'log_mailto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3-dev on:
 *
 * Wed Aug  4 22:47:56 2010
 *
 * @method     LogMailtoQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     LogMailtoQuery orderByMailId($order = Criteria::ASC) Order by the mail_id column
 * @method     LogMailtoQuery orderByMailto($order = Criteria::ASC) Order by the mailto column
 * @method     LogMailtoQuery orderByState($order = Criteria::ASC) Order by the state column
 * @method     LogMailtoQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method     LogMailtoQuery orderBySentAt($order = Criteria::ASC) Order by the sent_at column
 * @method     LogMailtoQuery orderByTries($order = Criteria::ASC) Order by the tries column
 * @method     LogMailtoQuery orderByError($order = Criteria::ASC) Order by the error column
 *
 * @method     LogMailtoQuery groupById() Group by the id column
 * @method     LogMailtoQuery groupByMailId() Group by the mail_id column
 * @method     LogMailtoQuery groupByMailto() Group by the mailto column
 * @method     LogMailtoQuery groupByState() Group by the state column
 * @method     LogMailtoQuery groupByCreatedAt() Group by the created_at column
 * @method     LogMailtoQuery groupBySentAt() Group by the sent_at column
 * @method     LogMailtoQuery groupByTries() Group by the tries column
 * @method     LogMailtoQuery groupByError() Group by the error column
 *
 * @method     LogMailtoQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     LogMailtoQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     LogMailtoQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     LogMailtoQuery leftJoinLogMail($relationAlias = '') Adds a LEFT JOIN clause to the query using the LogMail relation
 * @method     LogMailtoQuery rightJoinLogMail($relationAlias = '') Adds a RIGHT JOIN clause to the query using the LogMail relation
 * @method     LogMailtoQuery innerJoinLogMail($relationAlias = '') Adds a INNER JOIN clause to the query using the LogMail relation
 *
 * @method     LogMailto findOne(PropelPDO $con = null) Return the first LogMailto matching the query
 * @method     LogMailto findOneOrCreate(PropelPDO $con = null) Return the first LogMailto matching the query, or a new LogMailto object populated from the query conditions when no match is found
 *
 * @method     LogMailto findOneById(int $id) Return the first LogMailto filtered by the id column
 * @method     LogMailto findOneByMailId(int $mail_id) Return the first LogMailto filtered by the mail_id column
 * @method     LogMailto findOneByMailto(string $mailto) Return the first LogMailto filtered by the mailto column
 * @method     LogMailto findOneByState(string $state) Return the first LogMailto filtered by the state column
 * @method     LogMailto findOneByCreatedAt(string $created_at) Return the first LogMailto filtered by the created_at column
 * @method     LogMailto findOneBySentAt(string $sent_at) Return the first LogMailto filtered by the sent_at column
 * @method     LogMailto findOneByTries(int $tries) Return the first LogMailto filtered by the tries column
 * @method     LogMailto findOneByError(string $error) Return the first LogMailto filtered by the error column
 *
 * @method     array findById(int $id) Return LogMailto objects filtered by the id column
 * @method     array findByMailId(int $mail_id) Return LogMailto objects filtered by the mail_id column
 * @method     array findByMailto(string $mailto) Return LogMailto objects filtered by the mailto column
 * @method     array findByState(string $state) Return LogMailto objects filtered by the state column
 * @method     array findByCreatedAt(string $created_at) Return LogMailto objects filtered by the created_at column
 * @method     array findBySentAt(string $sent_at) Return LogMailto objects filtered by the sent_at column
 * @method     array findByTries(int $tries) Return LogMailto objects filtered by the tries column
 * @method     array findByError(string $error) Return LogMailto objects filtered by the error column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseLogMailtoQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseLogMailtoQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'LogMailto', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new LogMailtoQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    LogMailtoQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof LogMailtoQuery) {
			return $criteria;
		}
		$query = new LogMailtoQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    LogMailto|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = LogMailtoPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    LogMailtoQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(LogMailtoPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    LogMailtoQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(LogMailtoPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     int|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    LogMailtoQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(LogMailtoPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the mail_id column
	 * 
	 * @param     int|array $mailId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    LogMailtoQuery The current query, for fluid interface
	 */
	public function filterByMailId($mailId = null, $comparison = null)
	{
		if (is_array($mailId)) {
			$useMinMax = false;
			if (isset($mailId['min'])) {
				$this->addUsingAlias(LogMailtoPeer::MAIL_ID, $mailId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($mailId['max'])) {
				$this->addUsingAlias(LogMailtoPeer::MAIL_ID, $mailId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(LogMailtoPeer::MAIL_ID, $mailId, $comparison);
	}

	/**
	 * Filter the query on the mailto column
	 * 
	 * @param     string $mailto The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    LogMailtoQuery The current query, for fluid interface
	 */
	public function filterByMailto($mailto = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($mailto)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $mailto)) {
				$mailto = str_replace('*', '%', $mailto);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(LogMailtoPeer::MAILTO, $mailto, $comparison);
	}

	/**
	 * Filter the query on the state column
	 * 
	 * @param     string $state The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    LogMailtoQuery The current query, for fluid interface
	 */
	public function filterByState($state = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($state)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $state)) {
				$state = str_replace('*', '%', $state);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(LogMailtoPeer::STATE, $state, $comparison);
	}

	/**
	 * Filter the query on the created_at column
	 * 
	 * @param     string|array $createdAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    LogMailtoQuery The current query, for fluid interface
	 */
	public function filterByCreatedAt($createdAt = null, $comparison = null)
	{
		if (is_array($createdAt)) {
			$useMinMax = false;
			if (isset($createdAt['min'])) {
				$this->addUsingAlias(LogMailtoPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($createdAt['max'])) {
				$this->addUsingAlias(LogMailtoPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(LogMailtoPeer::CREATED_AT, $createdAt, $comparison);
	}

	/**
	 * Filter the query on the sent_at column
	 * 
	 * @param     string|array $sentAt The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    LogMailtoQuery The current query, for fluid interface
	 */
	public function filterBySentAt($sentAt = null, $comparison = null)
	{
		if (is_array($sentAt)) {
			$useMinMax = false;
			if (isset($sentAt['min'])) {
				$this->addUsingAlias(LogMailtoPeer::SENT_AT, $sentAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($sentAt['max'])) {
				$this->addUsingAlias(LogMailtoPeer::SENT_AT, $sentAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(LogMailtoPeer::SENT_AT, $sentAt, $comparison);
	}

	/**
	 * Filter the query on the tries column
	 * 
	 * @param     int|array $tries The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    LogMailtoQuery The current query, for fluid interface
	 */
	public function filterByTries($tries = null, $comparison = null)
	{
		if (is_array($tries)) {
			$useMinMax = false;
			if (isset($tries['min'])) {
				$this->addUsingAlias(LogMailtoPeer::TRIES, $tries['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($tries['max'])) {
				$this->addUsingAlias(LogMailtoPeer::TRIES, $tries['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(LogMailtoPeer::TRIES, $tries, $comparison);
	}

	/**
	 * Filter the query on the error column
	 * 
	 * @param     string $error The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    LogMailtoQuery The current query, for fluid interface
	 */
	public function filterByError($error = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($error)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $error)) {
				$error = str_replace('*', '%', $error);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(LogMailtoPeer::ERROR, $error, $comparison);
	}

	/**
	 * Filter the query by a related LogMail object
	 *
	 * @param     LogMail $logMail  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    LogMailtoQuery The current query, for fluid interface
	 */
	public function filterByLogMail($logMail, $comparison = null)
	{
		return $this
			->addUsingAlias(LogMailtoPeer::MAIL_ID, $logMail->getId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the LogMail relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    LogMailtoQuery The current query, for fluid interface
	 */
	public function joinLogMail($relationAlias = '', $joinType = Criteria::LEFT_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('LogMail');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'LogMail');
		}
		
		return $this;
	}

	/**
	 * Use the LogMail relation LogMail object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    LogMailQuery A secondary query class using the current class as primary query
	 */
	public function useLogMailQuery($relationAlias = '', $joinType = Criteria::LEFT_JOIN)
	{
		return $this
			->joinLogMail($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'LogMail', 'LogMailQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     LogMailto $logMailto Object to remove from the list of results
	 *
	 * @return    LogMailtoQuery The current query, for fluid interface
	 */
	public function prune($logMailto = null)
	{
		if ($logMailto) {
			$this->addUsingAlias(LogMailtoPeer::ID, $logMailto->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseLogMailtoQuery
