<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_guard_user_permission' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3-dev on:
 *
 * Wed Aug  4 22:47:57 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfGuardPlugin.lib.model
 */
class sfGuardUserPermissionQuery extends BasesfGuardUserPermissionQuery {

} // sfGuardUserPermissionQuery
