<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/08/04 23:15:12
sfConfig::add(array(
  'app_sf_admin_dash_web_dir' => '/sfAdminDashPlugin',
  'app_sf_admin_dash_image_dir' => '/sfAdminDashPlugin/images/icons/',
  'app_sf_admin_dash_default_image' => 'config.png',
  'app_sf_admin_dash_resize_mode' => 'thumbnail',
  'app_sf_admin_dash_logout' => true,
  'app_sf_admin_dash_site' => 'MailBot Portal',
  'app_sf_admin_dash_include_path' => true,
  'app_sf_admin_dash_include_jquery_no_conflict' => false,
  'app_sf_admin_dash_login_route' => '@sf_guard_signin',
  'app_sf_admin_dash_logout_route' => '@sf_guard_signout',
  'app_sf_admin_dash_items' => array (
  'Current Mails' => 
  array (
    'url' => 'mb_mail',
  ),
  'Current Recipients' => 
  array (
    'url' => 'mb_mailto',
  ),
  'Past Mails' => 
  array (
    'url' => 'log_mail',
  ),
  'Past Recipients' => 
  array (
    'url' => 'log_mailto',
  ),
),
  'app_server' => 'devel',
  'app_url' => 'http://mailbot.devel.fen.uchile.cl',
));
