<?php


/**
 * Skeleton subclass for performing query and update operations on the 'cuenta' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Jun 30 13:45:21 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CuentaPeer extends BaseCuentaPeer {


} // CuentaPeer
