<?php



/**
 * Skeleton subclass for representing a row from the 'log_mail' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3-dev on:
 *
 * Fri Jul  2 17:06:02 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class LogMail extends BaseLogMail {
  
  public function  __toString() {
    return '[' . $this->getId() . '] ' .substr($this->getSubject(), 0, 30);
  }
  
  public function getNbSuccessRecipients()
  {
    return LogMailPeer::getNbRecipientsByState($this->getId(), 'ok');
  }

  public function getProgress()
  {
    return $this->getNbSuccessRecipients() . '/' . $this->getNbRecipients();
  }

  public function getNbErrorRecipients()
  {
    return LogMailPeer::getNbRecipientsByState($this->getId(), 'error');
  }

  public function getNbErrors()
  {
    return $this->getNbErrorRecipients();
  }

  public function getNbRecipients()
  {
    return LogMailPeer::getNbRecipientsByState($this->getId());
  }

  public function getSubjectClean()
  {
    return iconv("UTF-8", "ISO-8859-1", $this->getSubject());
  }

  public function getBodyHtmlClean()
  {
    return iconv("UTF-8", "ISO-8859-1", $this->getBodyHtml());
  }

  public function getBodyTextClean()
  {
    return iconv("UTF-8", "ISO-8859-1", $this->getBodyText());
  }
} // LogMail
