<?php



/**
 * Skeleton subclass for performing query and update operations on the 'log' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3-dev on:
 *
 * Fri Jul  2 14:38:28 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class LogQuery extends BaseLogQuery {

} // LogQuery
