<?php



/**
 * Skeleton subclass for performing query and update operations on the 'mb_mailto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3-dev on:
 *
 * Wed Jun 30 17:42:01 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class MbMailtoQuery extends BaseMbMailtoQuery {

} // MbMailtoQuery
