<?php


/**
 * Skeleton subclass for representing a row from the 'mb_mail_attachment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Jun  8 16:04:14 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MbMailAttachment extends BaseMbMailAttachment {

} // MbMailAttachment
