<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/08/04 23:05:59

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=mailbot2;host=localhost',
  'username' => 'usrmailbot',
  'password' => 'EcmvRRjqLXZCsYhJ',
  'encoding' => 'latin1',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
