<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/08/04 23:15:37
$this->security = array (
  'report' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
